name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/profile-summary-cards.yml"
      - "README.md"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate profile summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: mrshappy0
          UTC_OFFSET: -5
